# Generated by Django 3.1.2 on 2020-12-12 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('kind', models.CharField(max_length=255, verbose_name='Kind')),
                ('level', models.CharField(max_length=255, verbose_name='Level')),
                ('shift', models.CharField(max_length=255, verbose_name='Shift')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.campus')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Company')),
                ('score', models.FloatField()),
                ('logo_url', models.CharField(max_length=255, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_price', models.FloatField()),
                ('price_with_discount', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.CharField(max_length=10, verbose_name='Stard Date')),
                ('enrollment_semester', models.CharField(max_length=6, verbose_name='Enrollment Semester')),
                ('enabled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.course')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.university'),
        ),
    ]
